#!/bin/bash

API="177.227.149.12:56756"

echo "Creating test user..."

curl -s -X POST "$API/users" \
  -H "Content-Type: application/json" \
  -d '{
    "username": "Test User",
    "email": "test.user@example.com",
    "password": "test_password_123"
  }' | jq '.'

echo "Done"
